accounts/urls.py
from django.urls import path
from .views import * 

app_name = 'accounts'

urlpatterns = [
    path('login/',login_user, name='log_in'),
    path('logout/',logout_user, name='logout'),
    path('signup/', signap_user, name='signup'),
    path('change_password/', change_password, name='change_password'),
    path('reset_password/', reset_password, name='reset_password'),
    path('reset_password_done/', reset_password_done, name='reset_password_done'),
    path('reset_password_confirm/<str:token>/',reset_password_confirm,name='reset_password_confirm'),
    path('reset_password_complete/',reset_password_complete, name='reset_password_complete'),
    path('edit_profile/<int:id>',change_profile,name='edit_profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from root.sitemap import StaticViewSitemap , DynamicViewSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'static' : StaticViewSitemap, 
    'dynamic': DynamicViewSitemap   

}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('root.urls')),
    path('services/',include('services.urls')),
    path('accounts/', include('accounts.urls')),
    path('robots.txt/', include('robots.urls')),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
)
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

templates/register/change_pass.html
<form method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type ='submit'>change_pass</button>
</foem>
{% if messages %}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %}

templates/register/edit_profile.html
<form method = 'post'>
    {% csrf_token %}
    {{form.as_p}}
    <button type ='submit'>edit</button>
</foem>
{% if messages %}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %}

templates/register/login.html
<form method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <h3><a href = {% url "accounts:signup" %}>you dont have account?</a></h3>
    <h3><a href = {% url "accounts:reset_password" %}>fotget pass?</a></h3>
    <button type ='submit'>login</button>
</foem>
{% if messages %}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %}

templates/register/reset_pass.html
<form method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type ='submit'>send</button>
</foem>

{% if messages %}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %}

templates/register/reset_password_complete.html
<h3>your pass changed</h3>

templates/register/reset_password_confirm.html
<form method = 'post'>
    {% csrf_token %}
    {{form.as_p}}
    <button type ='submit'>change_pass</button>
</foem>


{% if messages %}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %}

templates/register/reset_password_done.html
<h3>we send for you a message pleass check it</h3>

templates/register/signup.html
<form method = 'post'>
    {% csrf_token %}
    {{form.as_p}}
    <button type ='submit'>signup</button>
</foem>


{% if messages %}
{% for message in messages %}
{{message}}
{% endfor %}
{% endif %}